blank_issues_enabled: false
contact_links:
  - name: Experiment
    about: Experiment
    title: ğŸ“–ã“ã“ã«ã‚¿ã‚¤ãƒˆãƒ«ã‚’è¨˜è¼‰
    labels: experiment
    assignees: kuto5046
  - name: Bug
    about: Bug
    title: ğŸš«ã“ã“ã«ãƒã‚°ã‚’è¨˜è¼‰
    labels: bug
    assignees: kuto5046
